- title: On Scrambling Phenomena for Randomly Initialized Recurrent Networks
  authors:
    - Vaggos Chatziafratis
    - Ioannis Panageas
    - Clayton Sanford
    - Stelios Stavroulakis
  date: '2018-08-02'
  tags:
    - NeurIPS 2022

- title: Another paper
  authors:
    - Vaggos Chatziafratis
    - Ioannis Panageas
    - Clayton Sanford
    - Stelios Stavroulakis
  date: '2018-08-03'
  tags:
    - NeurIPS 2022
