- id: arxiv:2208.02204
  image: images/papers/advteamgames.png
  extra-links:
    - type: source
      link: https://github.com/steliostavroulakis/AdversarialTeamGames

- id: arxiv:2111.04178

- id: arxiv:2203.12074
  tags:
    - NeurIPS 2022

- id: arxiv:2203.12056
  tags:
    - ICML 2022

- id: arxiv:2204.11407
  tags:
    - IJCAI 2022

- id: arxiv:2110.10614

- id: arxiv:2106.01969
  tags:
    - ICLR 2022

- id: arxiv:2109.04603
  tags:
    - SOSA 2022
