- title: On Scrambling Phenomena for Randomly Initialized Recurrent Networks
  authors:
    - Vaggos Chatziafratis
    - Ioannis Panageas
    - Clayton Sanford
    - Stelios Stavroulakis
  date: 2021-01-01
  tags:
    - NeurIPS 2022
